### ISSUE TITLE
multi-gpu training?

### ISSUE THREAD

**Issue by yangchuancv** [lzccccc/SMOKE#11]
does the code support Multi-GPU training? 
TypeError: zip argument #1 must support iteration
What does this error mean? How should I solve it?

**Comment by lucasjinreal** [comment]
I think this repo missed something, even don't have inference script.

**Comment by lzccccc** [comment]
Yes, It supports.
Did you initialize the dataloader correctly?

**Comment by lzccccc** [comment]
@jinfagang 
I suggest you first read the code thoroughly instead of jumping into such a hasty conclusion. :)

**Comment by yangchuancv** [comment]
> Yes, It supports.
> Did you initialize the dataloader correctly?

I did not change the code

**Comment by lzccccc** [comment]
> > Yes, It supports.
> > Did you initialize the dataloader correctly?
> 
> I did not change the code

Did you link the dataset as described in the README?
It sounds like your dataloader is None type.

**Comment by yangchuancv** [comment]
> > > Yes, It supports.
> > > Did you initialize the dataloader correctly?
> > 
> > 
> > I did not change the code
> 
> Did you link the dataset as described in the README?
> It sounds like your dataloader is None type.

the dataset is linked correctly, and single-gpu training is ok

**Comment by lzccccc** [comment]
> > > > Yes, It supports.
> > > > Did you initialize the dataloader correctly?
> > > 
> > > 
> > > I did not change the code
> > 
> > 
> > Did you link the dataset as described in the README?
> > It sounds like your dataloader is None type.
> 
> the dataset is linked correctly, and single-gpu training is ok

Could you elaborate more on your question? 
Maybe a screenshot of your terminal and configs you used.

**Comment by yangchuancv** [comment]
> elaborate
python tools/plain_train_net.py --config-file "configs/smoke_gn_vector.yaml" is ok
python tools/plain_train_net.py --num-gpus 4 --config-file "configs/smoke_gn_vector.yaml" gets the error above (TypeError: zip argument #1 must support iteration)

**Comment by lucasjinreal** [comment]
@lzccccc Sorry for my hasty conculusion, but where can I found a `demo` or `predict` or `inference` file load the model and predict on image then draw 3d box on it?
Or even, have a single forward process with model?

**Comment by lzccccc** [comment]
> > elaborate
> > python tools/plain_train_net.py --config-file "configs/smoke_gn_vector.yaml" is ok
> > python tools/plain_train_net.py --num-gpus 4 --config-file "configs/smoke_gn_vector.yaml" gets the error above (TypeError: zip argument #1 must support iteration)

I could not help you with the limited information you provided...

**Comment by lzccccc** [comment]
> @lzccccc Sorry for my hasty conculusion, but where can I found a `demo` or `predict` or `inference` file load the model and predict on image then draw 3d box on it?
> Or even, have a single forward process with model?

Please see the issue you opened.

**Comment by yangchuancv** [comment]
@lzccccc  the error is as below:
for data, iteration in zip(data_loader, range(start_iter, max_iter)):
TypeError: zip argument #1 must support iteration

the config used is same as the config provided in the repo

**Comment by lzccccc** [comment]
> @lzccccc the error is as below:
> for data, iteration in zip(data_loader, range(start_iter, max_iter)):
> TypeError: zip argument #1 must support iteration
> 
> the config used is same as the config provided in the repo

It's weird. I have never encountered this problem before.
I assumed your Python and Pytorch version is correct.

Do your graphics cards have enough memory for 32 batch size?

**Comment by yangchuancv** [comment]
solved

**Comment by litingsjj** [comment]
@yangchuancv I meet the same question.  How should I solve it? Thx

**Comment by cnexah** [comment]
I have the same problem. How do you solve it?

**Comment by FANzhaoxin666** [comment]
i sovle the problem by setting the num_works=0

**Comment by gjd2017** [comment]
> i sovle the problem by setting the num_works=0

Yes， I have the same problem，when I setting the num_works=0, it works.  How is that?

**Comment by gjd2017** [comment]
> > i sovle the problem by setting the num_works=0
> 
> Yes， I have the same problem，when I setting the num_works=0, it works. How is that?

@lzccccc  do you know that?
