### ISSUE TITLE
Training on Google Colab

### ISSUE THREAD

**Issue by Florijan-Iljazovic** [lzccccc/SMOKE#12]
I'm sorry for breaking in with the absolutely noob questions.

But I am trying to run your (great!) work on Google Colab, and when I try to train it, it starts training (it seems) but it never shows any information. Should it be like that ?

It's running for hours now in the background, still the same. Silently running, no info.

Thanks for any help!

**Comment by lzccccc** [comment]
Hi,Did you receive training log when running the script? It is supposed to print loss information at every 10 steps.I don't know how Google colab function, but maybe you can try with a really small batch size to see if it works.Regards,-------- 原始邮件 --------发件人： Florijan-Iljazovic <notifications@github.com>日期： 2020年5月16日周六 凌晨1:54收件人： lzccccc/SMOKE <SMOKE@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [lzccccc/SMOKE] Training info (#12)
I'm sorry for breaking in with the absolutely noob questions.
But I am trying to run your (great!) work on Google Colab, and when I try to train it, it starts training (it seems) but it never shows any information. Should it be like that ?
It's running for hours now in the background, still the same. Silently running, no info.
Thanks for any help!

**Comment by Florijan-Iljazovic** [comment]
Thanks for a prompt reply!
Yes, I was expecting something like that to be printed but didn't see anything. 
OK I'm gonna try to play with training configuration a little bit.

**Comment by Florijan-Iljazovic** [comment]
I couldn't really solve the problem, at least I identified it to be about Multi-GPU training on Google Colab. It doesn't work for me, never even starts training. 

I opted for single GPU training. 32 batch size is too big, I get CUDA out of memory. Training now with smaller batch sizes hopefully will achieve smth. At least I see the log!

Later I will try in eval only mode with your pretrained weights. So I'm interested if you can comment on where should I put those weights (model_final.pth) before running the script in eval_only mode somehow I can't find that info and it's too much code to digest all at once.

Thanks!

**Comment by lzccccc** [comment]
The weights file should be put under tools/logs/

**Comment by pra-dan** [comment]
@Florijan-Iljazovic  were you trying to train for a custom object ? How did it go ?
