### ISSUE TITLE
Result not very good on testing

### ISSUE THREAD

**Issue by lucasjinreal** [lzccccc/SMOKE#15]
Some sample image visualized

![image](https://user-images.githubusercontent.com/21303438/82299334-f7140180-99e7-11ea-8b25-58efcbd6d9fa.png)
![image](https://user-images.githubusercontent.com/21303438/82299402-0d21c200-99e8-11ea-90fc-14fd33b3635a.png)
![image](https://user-images.githubusercontent.com/21303438/82299423-1579fd00-99e8-11ea-8155-b6c203133a99.png)
![image](https://user-images.githubusercontent.com/21303438/82299439-1ad74780-99e8-11ea-9cc9-896da91dc9d6.png)
![image](https://user-images.githubusercontent.com/21303438/82299502-2fb3db00-99e8-11ea-8e3d-f7a1c4334112.png)

miss detection is seriously problem.

**Comment by Florijan-Iljazovic** [comment]
Hey man I'm just wondering did you use some existing repo for these nicely visualized boxes ? Or is it your custom work.
Thanks!
I like that the front side is shaded, and I'm lazy to do it myself.

**Comment by lyxbyr** [comment]
This is fantastic as it is! Please ignore these comments, I think you've done an incredible job for the community.

**Comment by beedotkiran** [comment]
Hello @jinfagang, 

We were using models trained on the train-set to predict on KITTI test set, and had poor detection results at the center of the image on nearby/close objects (most cases), as in your case.

We also tried training and predicting on the Lyft dataset in KITTI format. We observed the same effect missing predictions on nearby large objects.

Could you please share how you have resolved this problem ?

Thank you!

**Comment by nikhil-nakhate** [comment]
Hi @beedotkiran , Did you have a different set of classes in the Lyft dataset. I am not able to train on a dataset with different classes. Any help would be appreciated.

Best Regards,
Nikhil
