### ISSUE TITLE
No module named 'maskrcnn_benchmark'

### ISSUE THREAD

**Issue by nyg2017** [lzccccc/SMOKE#2]
I finished all the setup as your instruction. But when I getting start, the error is as follow.
``Traceback (most recent call last):
  File "tools/plain_train_net.py", line 9, in <module>
    from smoke.utils.check_point import DetectronCheckpointer
  File /MONO_3D/SMOKE/smoke/utils/check_point.py", line 8, in <module>
    from smoke.utils.model_zoo import cache_url
  File "/MONO_3D/SMOKE/smoke/utils/model_zoo.py", line 9, in <module>
    from maskrcnn_benchmark.utils.comm import is_main_process
ModuleNotFoundError: No module named 'maskrcnn_benchmark'

Did I need to install the maskrcnn?

**Comment by lzccccc** [comment]
Hi,

I have fixed it with the new commit.
Please check it.

**Comment by nyg2017** [comment]
> Hi,
> 
> I have fixed it with the new commit.
> Please check it.
Thx! it works.
