### ISSUE TITLE
projection of 3D center not on image plane

### ISSUE THREAD

**Issue by dashidhy** [lzccccc/SMOKE#20]
Hello @lzccccc . Thank you for making this amazing work open-source. I tried your code and found that some failure cases may due to out-of-image 3D centers, like the right- and left-first cars in the image below. So I was wondering do you include this kind of objects during training? If so, how do you assign keypoint labels to them? 

![failed_case](https://user-images.githubusercontent.com/24664403/84969909-820f1700-b0ce-11ea-935c-c88da18caf29.png)

**Comment by ZhxJia** [comment]
According to the paper in section 4.4, only 3D projected center points on the image plane are used for regression.
