### ISSUE TITLE
ModuleNotFoundError: No module named 'yacs'

### ISSUE THREAD

**Issue by Gironote** [lzccccc/SMOKE#25]
I follow the manual the  https://github.com/lzccccc/SMOKE
![image](https://user-images.githubusercontent.com/65701965/87895101-8177f080-ca7f-11ea-8153-a35b4770051d.png)
![image](https://user-images.githubusercontent.com/65701965/87895111-89d02b80-ca7f-11ea-827c-bb4a87495800.png)

but this code error occur $ python tools/plain_train_net.py --eval-only --config-file "configs/smoke_gn_vector.yaml"
![image](https://user-images.githubusercontent.com/65701965/87895164-a9ffea80-ca7f-11ea-8918-d161b545ca78.png)

**Comment by ssonje12** [comment]
Hey, I am getting the same issue, how did you solve it?

**Comment by Gironote** [comment]
I can solve this  problem by using anaconda  environment

2021년 2월 20일 (토) 오전 3:49, Saurabh <notifications@github.com>님이 작성:

**Comment by KunikaValecha** [comment]
solved it using "pip install yacs"
