### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../smoke/data/datasets/evaluation/kitti/kitti_eval'

### ISSUE THREAD

**Issue by Gironote** [lzccccc/SMOKE#26]
I place folder like this
![image](https://user-images.githubusercontent.com/65701965/87896035-05cb7300-ca82-11ea-8f1e-edc4c60c22b5.png)
![image](https://user-images.githubusercontent.com/65701965/87896043-0a902700-ca82-11ea-91cb-50956974016d.png)
![image](https://user-images.githubusercontent.com/65701965/87896046-0f54db00-ca82-11ea-9014-0f4472f54f32.png)

error occur
![image](https://user-images.githubusercontent.com/65701965/87896054-17147f80-ca82-11ea-86b2-cc3cb2c87b71.png)

so I made kitti_eval file and again
![image](https://user-images.githubusercontent.com/65701965/87896746-154bbb80-ca84-11ea-9e18-bde010f23002.png)
but error occur again

**Comment by KunikaValecha** [comment]
Hi, 
I came across same issue, actually the path given is wrong. Either you try to give the abs path to the file or you remove "../" i.e. changing to prev directory part in the path as it is in the same dir. This worked for me.

**Comment by Gironote** [comment]
thank you for reply

**Comment by no-Seaweed** [comment]
Hi, 

How did you remake "kitti_eval" folder? In previous issue, the author shared two links of evaluation code, and I git cloned the one in https://github.com/lzccccc/kitti_eval_offline. Should I copy paste label_2 and data to this folder as the README.md recommend and rename kitti_eval_offline to kitti_eval? I did these and get a different error. What else do I need to do? Or could you share the procedure of getting rid of the "No such file or directory" error step by step? Thanks in advance.

Best,
Shukai

**Comment by KunikaValecha** [comment]
Hi,
Have you tried creating a dir named "results" in root dir before running the code?
