### ISSUE TITLE
How MAX_ITERATION is calculated in smoke_gn_vector.yaml?

### ISSUE THREAD

**Issue by Xianpeng919** [lzccccc/SMOKE#30]
Hello!

First, thanks so much for releasing the code! It has very high quality and is very tidy and concise.

I wonder how the MAX_ITERATION is calculated. Is it calculated based on the number of images on 'trainval' ? In other words, 'trainval' has 7481 images, you trained it using batch_size=32 with 60 epochs. In my calculation, the total m will be 7481*60/32 =14026 iterations. However, in your config, MAX_ITERATION is 25000, about twice times as my calculation. Do I miss anything?

Thanks in advance!

**Comment by stefchel** [comment]
Hi @Xianpeng919,

I think your calculation is right. I assume the configured max_iteration in the config file is just some arbitrary number. If you look at the default configuration, you will see that 14500 iterations are used which are much closer to your calculated value.
https://github.com/lzccccc/SMOKE/blob/bc5d2bba66e2d66fa56b7b599d55457cb1a05b33/smoke/config/defaults.py#L128
