### ISSUE TITLE
Problems Training SMOKE on custom dataset

### ISSUE THREAD

**Issue by yqchau** [lzccccc/SMOKE#53]
I am training SMOKE on my own dataset with size (1920, 1208) and there are errors in the backbone. Note that I have changed the image size in the config. Please help.
<img width="578" alt="Screenshot 2021-06-22 at 1 21 21 PM" src="https://user-images.githubusercontent.com/65069848/122867981-ee190080-d35c-11eb-8c98-c649fd854dc8.png">

**Comment by ElectronicElephant** [comment]
IMHO, you should make sure that the input size `(w, h) % 32 == 0`

**Comment by yqchau** [comment]
Yes, it's been solved, thanks!
