### ISSUE TITLE
can you explain the targets attributes with trans_mat means when inference ?

### ISSUE THREAD

**Issue by SmallMunich** [lzccccc/SMOKE#61]
Hi, great works. I debug this code when I confused about the targets[i].get_field("trans_mat"). When to inference, the  targets[i].get_field("trans_mat") represent what?

**Comment by poledna** [comment]
Hi, have you ever figured **trans_mat** out ? 
What does it means other than 
```
    trans_mat = get_transfrom_matrix(
        center_size, 
        [cfg.INPUT.WIDTH_TRAIN // cfg.MODEL.BACKBONE.DOWN_RATIO,
         cfg.INPUT.HEIGHT_TRAIN // cfg.MODEL.BACKBONE.DOWN_RATIO]
    )
```
Im really confused because my pixel bbox prediction is correct but the placement of the keypoint is way off, i believe it might be this trans_mat.
Thanks
