### ISSUE TITLE
How did you get ~30ms on runtime?

### ISSUE THREAD

**Issue by tlgkyn06** [lzccccc/SMOKE#64]
Hi , I build and run your code on gtx 1080. 

Only model time cost is ~160ms, total fps is around 4fps. It can't be such a difference between ~30ms on Titan gpu and ~160ms on gtx 1080.

What is possible causes of this situation?

**Comment by tlgkyn06** [comment]
if I crop image I can increase fps , but for some image sizes I get "RuntimeError: The size of tensor a (63) must match the size of tensor b (62) at non-singleton dimension 2" error. What is minimum input size for default model?

**Comment by thuangb** [comment]
Make sure the width and height of your image after cropping are divisible by 4 or 8 because the downsampling operator in SMOKE can cause mismatched size
