### ISSUE TITLE
compile setup.py

### ISSUE THREAD

**Issue by fangjiaojiao** [lzccccc/SMOKE#8]
could I compile the setup.py in Win10.

**Comment by lzccccc** [comment]
Hi,

I haven't tried it and I do not recommend running codes under Windows OS.

**Comment by fangjiaojiao** [comment]
Thank you！

**Comment by Huangdebo** [comment]
I have implemented training and testing under window, you can go to have a look. Thanks to the author for the source code.
[smoke-window](https://github.com/Huangdebo/SMOKE-window)
