### ISSUE TITLE
How to start training without using a pretrained model

### ISSUE THREAD

**Issue by dandervis** [lzccccc/SMOKE#80]
Hello, thank you very much for your contribution, when I want to train my own dataset with your model, what do I need to do to train from scratch instead of loading the pre-trained model you provided, because my dataset category is not the same as kitti,when I do it like issue #69 , I still get the following issue, it looks like it's caused by your pretrained model still loaded
![Uploading 1666265005021.png…]()

**Comment by dandervis** [comment]
just like this
RuntimeError: Error(s) in loading state_dict for KeypointDetector:
        size mismatch for heads.predictor.class_head.3.weight: copying a param with shape torch.Size([3, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([10, 256, 1, 1]).
        size mismatch for heads.predictor.class_head.3.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([10]).

**Comment by dandervis** [comment]
by the way, I have revised configs/smoke_gn_vector.yaml 
#MODEL:
  #WEIGHT: "catalog://ImageNetPretrained/DLA34"

**Comment by pummi823** [comment]
Hello!!! I have you solve is ??
